### ISSUE TITLE
[International Draughts] GUI - Enhance History and Clock visibility

### ISSUE THREAD

**Issue by IgorLeMasson** [mi-g/joclyboard#12]
Users could have a way to control if the **History** (game notation) and **Clock** will stay always visible.
It is quite useful mostly to improve game time management and to be easier see the moves played.

**Comment by mi-g** [comment]
The idea in JoclyBoard is that when users play frequently a given game, they should use templates (just setup the windows the way you want, then click _Save template_). This way, the history and clock windows (visibility, size and position) are persisted when you start the template.

**Comment by IgorLeMasson** [comment]
The "Template" feature works well to save user settings, but it doesn't offer a way to show **History** and **Clock** at same time, it is the main goal.

**Comment by mi-g** [comment]
If you open a match, open the clock and history windows, then save as a template, whenever you start this template, the clock and history windows open automatically. Isn't it what we are talking about ?

**Comment by IgorLeMasson** [comment]
I expected see the **Board** window _maximized_, and **History** and **Clock** simultaneously in same fashion of others draughts softwares GUIs, but as this layout is only possible if the **Board** window is under _reduced_ size. Actually it is is not a critical issue, but this tip could be described in user Help.

**Comment by mi-g** [comment]
Oh i see, you mean having the history and clock windows on top of the board window. Yes, that makes much sense and shouldn't be too hard to setup. I'll come back on this with a solution.

**Comment by IgorLeMasson** [comment]
Add a window joining Board + Clock + History would be nice, it will enhance the visibiity, but in my point of view, the current design should be kept, since it is very flexible, allowing set each window size and position. 

**Update**: I have tested "_Save template_" feature, trying to fix these windows: **Board**, **History**, **Clock**, '**Possible Moves**' and **Players**, but I verified that Players window position doesn't persist when the saved template is loaded.

![windows_screenshot1](https://cloud.githubusercontent.com/assets/8975474/26814468/3819f09c-4a5c-11e7-8e62-b586cd739304.png)

That limitation brought me an insight, why not add the players names on the board window?

**Comment by mi-g** [comment]
There is no need to persist the Players window as this is input-only data and those data are persisted.
In addition to the board window, the 3 windows that are persisted in a template are history, clock and possible moves.
Adding player names in the board window would waste space for no real benefit.

**Comment by IgorLeMasson** [comment]
> There is no need to persist the Players window as this is input-only data and those data are persisted.
Keep the names visible is useful to double-check the names, when we have 2 instances of JoclyBoard playing a DXP match for instance

**Comment by mi-g** [comment]
Note that the names appear in the clock window.

**Comment by IgorLeMasson** [comment]
Yes, I see it. But I was trying be sure each one is White or Black :) But it have checked that is persistent (White on left and Black on right).

**Comment by mi-g** [comment]
Depending on the game (or even the skin), it can be yellow/red, red/blue, ... This is why in Jocly the distinction is A (playing the first move) and B, and JoclyBoard provides the ability to rename the player.

**Comment by mi-g** [comment]
Pushed to master branch: History, Clock and Moves windows are now children (i.e always on top) of the board window.
This will be in the next 0.9.11 release.
