### ISSUE TITLE
Installed CECP engine does not play

### ISSUE THREAD

**Issue by fsmosca** [mi-g/joclyboard#16]
I use JoclyBoard 0.9.12 on windows 7 and installed fairy-max engine attempting to setup capablanca variant.

Engine Config:

![image](https://user-images.githubusercontent.com/22366935/28994996-c2b403c8-7991-11e7-94bd-3212f589edd2.png)

Setup capablanca game, change player then save. 

![image](https://user-images.githubusercontent.com/22366935/28995020-7ab0b55c-7992-11e7-81ac-8a28a95b225c.png)

Play a move and the engine does not play.

I am using the following Fairy-Max, tested on winboard GUI and it would play.

> feature myname="Fairy-Max 4.8V"
> feature memory=1
> feature setboard=0 xedit=1 ping=1 done=0
> feature variants="normal,nocastle,shatranj,asean,makruk,cambodian,ai-wok,courier
> ,knightmate,capablanca,gothic,falcon,cylinder,berolina,super,seirawan,spartan,gr

How this is done correctly to work in JoclyBoard?

**Comment by MineProjectZ** [comment]
you are right. i testet it with faitymax from winboard 4.8 and it also dont worked. but yesterday it worked with the 4.7 version.

**Comment by fsmosca** [comment]
@MineProjectZ 

I downloaded winboad 4.7.3 here.
http://www.open-aurec.com/wbforum/viewtopic.php?f=19&t=51528&start=4

It contains fairy-max 4.8S

It still does not work.

What do you mean by 4.7 version? Winboard 4.7 or Fairy-Max 4.7?

**Comment by MineProjectZ** [comment]
Fairy max

**Comment by mi-g** [comment]
Your setup is incorrect. In the [engines documentation page](https://github.com/mi-g/joclyboard/wiki/Game-Engines#fairymax.capablanca), the fields *Game*, *Protocol* and *Details* are there to organize the manual and they should not appear in the config. Actually, your config should just be:

```
variant: capablanca
```

I gave it a try using FairyMax 4.8V (standard version on Ubuntu 17.04) and it worked without problem.

Please confirm it now works for you and close this issue.

**Comment by fsmosca** [comment]
@mi-g 

I am now using the following setting, but still does not work. I am on windows 7.

![image](https://user-images.githubusercontent.com/22366935/29163519-58db1448-7def-11e7-815c-c156b36458aa.png)

**Comment by fsmosca** [comment]
@MineProjectZ 

Where did you get the Fairy-Max v4.7?, I assume your are using windows OS.

**Comment by MineProjectZ** [comment]
In my winboard 4.7 was fairy Max 4.7

**Comment by fsmosca** [comment]
@MineProjectZ 

I try to find the Fairy-Max 4.7 but could not find it.

Winboard 4.6.2, Fairy-Max 4.8Rt
Winboard 4.5.3, Fairy-Max 4.8R
Winboard 4.4.4, Fairy-Max 4.80
Winboard 4.7.3, Fairy-Max 4.8S

So perhaps Fairy-Max 4.7 is from an older winboard beyond 4.6.2.

I stop searching this version now. It is better to try the latest version of it.

**Comment by fsmosca** [comment]
@mi-g 

I tried to log Fairy-Max sent and received commands, but get nothing because, Jocly failed to load the Fairy-Max engine. I can also observe Fairy-Max cannot be found in Windows Task Manager after starting the game.

I tried changing the engine paths but it seems like JoclyBoard failed to find the engine.
The following has been tried but failed.
```
c:\engines\fmax.exe
c:\\engines\\fmax.exe
c:/engines/fmax.exe
```

**Comment by mi-g** [comment]
Can you run FairyMax manually from `cmd` or `powershell` by typing the command `c:\engines\fmax.exe` ?

**Comment by mi-g** [comment]
Try this as your `Details` field:
```
variant: capablanca
workingDir: c:\\engines
debug: 1
```

**Comment by fsmosca** [comment]
@mi-g 

> Can you run FairyMax manually from cmd or powershell by typing the command c:\engines\fmax.exe ?

fmax does not run, it has problem reading fmax.ini file.

![image](https://user-images.githubusercontent.com/22366935/29201291-91e38c7a-7e8f-11e7-8034-0bae5b02bd28.png)

**Comment by fsmosca** [comment]
@mi-g 

This one works, thank you.
```
variant: capablanca
workingDir: c:\\engines
debug: 1
```
