### ISSUE TITLE
building joclyboard dont works

### ISSUE THREAD

**Issue by MineProjectZ** [mi-g/joclyboard#17]
when i follow this instructions https://github.com/mi-g/joclyboard/wiki/Installing-JoclyBoard-from-Github joclyboard wont start after i rum the electron app command. in the task manager i see that the electron app is running, but there is no gui.

**Comment by mi-g** [comment]
Please provide more details: what OS/version you are running on, any console message you get, ...

**Comment by MineProjectZ** [comment]
I am running Windows 10 and in the console I get no message

**Comment by mi-g** [comment]
I went through the whole git clone/install/run process on Windows 10 and didn't have any problem, the main window appeared correctly.
Does running the official JoclyBoard build works for you ?

**Comment by MineProjectZ** [comment]
Yes

**Comment by mi-g** [comment]
Did you execute the `npm run app-install` correctly ?

**Comment by MineProjectZ** [comment]
Yes

**Comment by mi-g** [comment]
Sorry to ask, but why do you need to execute JoclyBoard directly from git ? I mean your answers are very concise so i guess you haven't made any investigation on your own. Normally, if you need to run the app from its source code, this is because you want to modify something or at least learn how it works. This means you should have a development environment that would make finding your issue very easy.

**Comment by MineProjectZ** [comment]
after i get it to work, i want to make a privat version with my own variants.

**Comment by mi-g** [comment]
so you need to setup a development environment. i personally Visual Studio Code for both Jocly core and JoclyBoard. It allows to run JoclyBoard/node.js from a debugger. There are other IDEs that allows doing this.

**Comment by MineProjectZ** [comment]
i have visula studio code installed

**Comment by MineProjectZ** [comment]
i tried to reinstall joclyboard but now i get this error, when i make npm install. maybe this was also at the first installation:
npm WARN retry will retry, error on last attempt: Error: EBUSY: resource busy or locked, rename 'C:\Users\KANNMA~1\AppData\Local\Temp\npm-6048-4ea13e18\registry.npmjs.org\macaddress\-\macaddress-0.2.8.tgz.1000603157' -> 'C:\Users\KANNMA~1\AppData\Local\Temp\npm-6048-4ea13e18\registry.npmjs.org\macaddress\-\macaddress-0.2.8.tgz'
npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v6.11.0
npm ERR! npm  v3.10.10

npm ERR! tarball.destroy is not a function
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
npm WARN retry will retry, error on last attempt: Error: EBUSY: resource busy or locked, rename 'C:\Users\KANNMA~1\AppData\Local\Temp\npm-6048-4ea13e18\registry.npmjs.org\require-directory\-\require-directory-2.1.1.tgz.4023526726' -> 'C:\Users\KANNMA~1\AppData\Local\Temp\npm-6048-4ea13e18\registry.npmjs.org\require-directory\-\require-directory-2.1.1.tgz'
npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v6.11.0
npm ERR! npm  v3.10.10

npm ERR! tarball.destroy is not a function
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
npm WARN retry will retry, error on last attempt: Error: EBUSY: resource busy or locked, rename 'C:\Users\KANNMA~1\AppData\Local\Temp\npm-6048-4ea13e18\registry.npmjs.org\require-directory\-\require-directory-2.1.1.tgz.2946221359' -> 'C:\Users\KANNMA~1\AppData\Local\Temp\npm-6048-4ea13e18\registry.npmjs.org\require-directory\-\require-directory-2.1.1.tgz'
npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v6.11.0
npm ERR! npm  v3.10.10

npm ERR! tarball.destroy is not a function
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

**Comment by mi-g** [comment]
The version of node.js i use is 7.6.0 maybe this is the reason. You should try to update node.js to verify.
Also, when things go wrong like this, you can remove the `node_modules` directories (the one in the top directory and the one in the `app` sub-directory. Then execute `npm install` and  `npm run app-install` to force the reinstallation of the dependencies.

**Comment by MineProjectZ** [comment]
i try it

**Comment by MineProjectZ** [comment]
thank you, it worked

**Comment by mi-g** [comment]
Good ! I can close the bug now.
By the way, was the issue about the node.js version or a messed up `node_modules` directory ?
For the records, it is very important (and not only for Jocly projects) to check the errors at any command and not just follow what's in the tutorial as there are many reasons for things to go wrong at any time.

**Comment by MineProjectZ** [comment]
node.js version

**Comment by MineProjectZ** [comment]
by the way, how i replace the jocly npm module with my jocly fork?

**Comment by mi-g** [comment]
On Linux or Mac, you do a `npm link <jocly directory>`, so when you do the `npm install` and `npm run install`, the system picks the Jocly module in development instead of downloading the Jocly released package from the web.
I think it should work on Windows, even if the internal mechanism is not the same (it creates a symbolic link on unix based systems, but this does not exist on Windows). If this does not work, try searching `npm link for windows` on the web.

**Comment by MineProjectZ** [comment]
should i do the gulp build before npm link?

**Comment by mi-g** [comment]
No, you must:
1. delete directories `node_modules` in the project directory and `app` sub-directory
2. run `npm link your-jocly-directory`
3. run `npm install` and `npm run-app-install`
4. run `gulp build`
