### ISSUE TITLE
[International Draughts] GUI - Allow easiest user actions for mandatory capture and move

### ISSUE THREAD

**Issue by IgorLeMasson** [mi-g/joclyboard#9]
When there is only a unique possible capture, the user interface could allow the movement just doing double-clicking on the piece that is "capturer" (square 31 on attached screenshots) or doing a double-click on the square where the piece will stay after whole capture movement (square 21 on attached screenshots).

![capture_screen1](https://cloud.githubusercontent.com/assets/8975474/26757862/a95f7f04-48a1-11e7-97b1-fbd4ab829d01.png)

![capture_screen2](https://cloud.githubusercontent.com/assets/8975474/26757863/a965c2ce-48a1-11e7-8eb8-d35647b61dd4.png)

The same issue happens for a selected piece which as a unique possible move.

**Comment by mi-g** [comment]
That should be the case, at least for International Draughts.
Can you check in the view options, parameter _Auto-complete moves_ ? If it is set, clicking the initial piece when there is no ambiguity should be enough to validate the move. _Auto-complete moves_ should be on by default.
Note that it is a single click, as double click does not match the underlying Web technology too well.

**Comment by IgorLeMasson** [comment]
Many thanks for your tip!
The **_Auto-complete moves_** works when double-click is done on selected piece to move (square **31** on given first screenshots), but it does not works when the end square is double-clicked (square **21** on given screenshots).

**Comment by mi-g** [comment]
I checked the source code and _autoComplete_ is true by default on _International Draughts_.
Note that it's not easy to verify because this parameter uses the last value that has been set, so you need to remove the configuration file and restart JoclyBoard to see what the default is.
Also it's always single click, and you indeed need to click on the piece to move, not the target position. I don't think we need both mechanisms.

**Comment by IgorLeMasson** [comment]
> I checked the source code and autoComplete is true by default on International Draughts.
> Note that it's not easy to verify because this parameter uses the last value that has been set, so you need to remove the configuration file and restart JoclyBoard to see what the default is.

I'm not sure but I guess after install JoclyBoard the _autoComplete_ option was disabled.

**Comment by mi-g** [comment]
You can try to quit the app, remove the config file and restart JoclyBoard.
The config file location is [described here](https://github.com/nathanbuchar/electron-settings/wiki/FAQs#where-is-the-settings-file-saved)

**Comment by mi-g** [comment]
As far as i can tell, the auto-complete feature works as expected.
